# Generated by Django 6.0.7 on 2026-08-09 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('user_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='service_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='user_services.servicebooking'),
        ),
    ]
