# Generated by Django 6.0.7 on 2026-08-10 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('rooms', '0003_room_gender_preference_room_room_type'),
        ('user_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='service_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='user_services.servicebooking'),
        ),
        migrations.AlterField(
            model_name='review',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rooms.room'),
        ),
    ]
