# Generated by Django 6.0.7 on 2026-08-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('BOOKING', 'Booking'), ('SERVICE_BOOKING_ACCEPTED', 'Service Booking Accepted'), ('SERVICE_BOOKING_REJECTED', 'Service Booking Rejected'), ('SERVICE_BOOKING_CANCELLED', 'Service Booking Cancelled'), ('SERVICE_COMPLETED', 'Service Completed'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_SUCCESS', 'Payment Successful'), ('MESSAGE', 'Message'), ('REVIEW', 'Review')], max_length=50),
        ),
    ]
